### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by n0j0** [dz0ny/mopidy-lux#2]
Hi, I have just found out about Mopidy and am looking for an http client. Based on the screenshots, Lux looks exactly like what I am looking for with browse and discover. 

So I have been trying to install lux but no luck. I am not familiar with pip but I had other http clients work for me by just copying static files to a dir and point mopidy.conf to it. 

I have tried both copying the contents of the mopidy-lux/static folder and even building from source but I always only see the left navbar and then a blank page, no content, no matter what I click.

Any help with how to get this running would be greatly appreciated!

--n0j0

**Comment by ianmxyz** [comment]
I think the problem is that this link isn't working, so pip won't install it.

https://pypi.python.org/pypi/Mopidy-Lux/

Personally I don't know how you get round that.

**Comment by evanjd** [comment]
To install, clone the repo and/or download the ZIP directly from Github. Once downloaded, run the following command from the root directory of Mopidy-Lux (using sudo if needed, assuming you're using *nix).

```
python setup.py install
```

Keep an eye out for errors, my first install was unsuccessful because of some missing dependencies, but the installer told me how to fix them.

There's no need to configure mopidy to use Lux, it gets loaded as an extension automatically. However, mopidy-lux breaks mopidy for me! I get served the following error on startup:

```
ERROR    'module' object has no attribute 'Router'
```

After which it shuts down. The tracepath points to Mopidy-Lux.

**Comment by badbroetchen** [comment]
could not believe that the manual installation will destroy my running mopidy installation... learned. 
Could fix it for me by installing setup.py again with parameter --record

pi@raspberrypi ~//mopidy-lux $ sudo python setup.py install --record logfile.txt

now there should be a: "writing list of installed files to 'logfile.txt'" in last line.

With the command: "sudo rm $(cat logfile.txt)" the installed files was removed and Mopidy starts without error message...

**Comment by evanjd** [comment]
If you have pip installed, here's an easier way:

```
pip uninstall Mopidy-Lux
```

**Comment by badbroetchen** [comment]
@evanjd 
did you get it working with mopidy-lux, too? On any way?

**Comment by evanjd** [comment]
@badbroetchen No, but I didn't try anything. It looks like Mopidy-Lux is dependent on a now deprecated/removed HTTP API class in Mopidy. Short version: Mopidy changed something that broke compatibility with Mopidy-Lux, the dev needs to update his extension to get it working again.

**Comment by badbroetchen** [comment]
@evanjd Thank you for this information. Actually i´m not a linux-crack - only playing around in some cases on my Pi - so i will hold out for a fix.

**Comment by jodal** [comment]
For the record, the API changes in Mopidy which Lux depends on has never been part of a Mopidy release. It is new in the upcoming Mopidy 0.19.

You're trying to run a (now outdated) development snapshot of a client which depends on a development snapshot of the server.

**Comment by dz0ny** [comment]
State: Unreleased

Future development TBD.
